## Numpy

In [1]:
import numpy as np

In [4]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## Numpy Arrays (ndarray)

In [6]:
 np.array([1, 2, 3])

array([1, 2, 3])

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [19]:
type(matrix[0][0])

numpy.complex128

In [20]:
type(1)

int

In [21]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [26]:
ndarray = np.array([1, 2, 3], dtype=np.float64)

In [28]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

## ndarrayの演算

In [30]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [31]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [40]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [42]:
ndarray + 3

array([4., 5., 6.])

## Shape

## .shape

In [46]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
ndarray.shape

(3, 2)

In [50]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])
print(ndarray1.shape)
print(ndarray2.shape)

(3,)
(1, 3)


In [58]:
expand_ndarray = np.expand_dims(ndarray1, axis=-1)

In [59]:
expand_ndarray.shape

(3, 1)

In [60]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [61]:
expand_ndarray

array([[1],
       [2],
       [3]])

In [65]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [67]:
ndarray = np.array([1, 2, 3, 4])

In [68]:
ndarray

array([1, 2, 3, 4])

In [70]:
ndarray[-1]

4

In [72]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
ndarray[0, 1]

2

In [76]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [77]:
ndarray[1:3]

array([2, 3])

In [85]:
ndarray[:3]

array([1, 2, 3])

In [79]:
ndarray[1:]

array([2, 3, 4])

In [82]:
ndarray[:-2]

array([1, 2])

In [83]:
ndarray[:]

array([1, 2, 3, 4])

In [87]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
ndarray[:3, 1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [96]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
ndarray[:3][1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
ndarray[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

## np.arange(), np.linspace(), np.logspace()

In [103]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [107]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [110]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [111]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [112]:
10  ** np.linspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

## np.zeros(shape)

In [114]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
np.zeros(3)

array([0., 0., 0.])

## np.ones(shape)

In [117]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
np.ones(3)

array([1., 1., 1.])

In [120]:
np.ones((5, 4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## np.eye()

In [121]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.randomを使って乱数生成

### np.random.rand()

In [149]:
np.random.rand(3, 4)

array([[0.15654983, 0.23222104, 0.95095686, 0.15342159],
       [0.25802629, 0.51049562, 0.60338406, 0.02088477],
       [0.54084028, 0.94883628, 0.24066961, 0.62066815]])

### np.random.seed

In [176]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [177]:
np.random.rand()

0.7203244934421581

### np.random.randn()

In [205]:
np.random.randn(3, 4)

array([[-0.23643695,  0.7278135 ,  0.51507361, -2.78253447],
       [ 0.58464661,  0.32427424,  0.02186284, -0.46867382],
       [ 0.85328122, -0.41302931,  1.83471763,  0.56438286]])

In [228]:
np.random.normal(10, 1)

9.964632075121289

### np.random.randint()

In [235]:
np.random.randint(10, 100, (2, 3))

array([[11, 51, 65],
       [65, 74, 25]])

### np.random.choice()

In [245]:
a = [1, 2, 3]
np.random.choice(a)

1

In [246]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [259]:
idx = np.random.choice(index_pool)
idx

0

In [260]:
ndarray[idx]

array([1, 2, 3, 4])

In [249]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 統計量を求める

In [308]:
std_norm = np.random.randn(5, 5)
std_norm

array([[-7.78219883e-01,  3.21902039e-02,  1.23901381e-01,
        -1.13165968e-03, -1.83037991e+00],
       [ 5.68835931e-01, -1.22872028e+00, -1.03482157e-01,
         7.61991950e-02,  6.63131261e-01],
       [ 6.92051866e-01, -4.95984064e-01,  2.61961858e+00,
         3.12907152e-01, -1.02903784e+00],
       [ 4.91497609e-01,  1.30294459e+00, -7.42290121e-01,
        -2.48578107e-02, -8.78109127e-01],
       [ 6.60861785e-01,  1.00393167e+00, -5.54488891e-01,
         1.45412397e+00, -8.80236681e-01]])

In [320]:
std_norm.max(axis=1)

array([0.12390138, 0.66313126, 2.61961858, 1.30294459, 1.45412397])

In [309]:
np.max(std_norm)

2.619618584256357

In [310]:
std_norm.min()

-1.830379910147331

In [311]:
std_norm.argmax()

12

In [312]:
std_norm.flatten()[std_norm.argmax()]

2.619618584256357

In [313]:
std_norm.mean()

0.058210271179974064

In [314]:
np.median(std_norm)

0.03219020387445077

In [315]:
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))

median took 0.01232004165649414 sec
mean took 0.0005559921264648438 sec


In [316]:
np.mean(a)

-0.0009094129158929686

In [317]:
time.time()

1603506869.7660556

In [318]:
np.std(std_norm)

0.9555027757938377

## 数学で使う便利関数

### np.sqrt()

In [321]:
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

### np.log(ndarray)

In [331]:
x = np.linspace(1, 10, 10)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [332]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [336]:
np.exp(np.log(1))

1.0

In [337]:
np.e

2.718281828459045

In [339]:
array = np.arange(1,11)
np.sum(array)

55

In [341]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [343]:
np.sum(ndarray, axis=1)

array([15, 40])

In [345]:
array = np.arange(-10, 0)
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.isnan()

In [346]:
np.log(-1)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [348]:
type(np.nan)

float

In [349]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [353]:
np.log(-100) == np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


False

## その他便利関数

### np.clip()

In [362]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [363]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [364]:
1e-4

0.0001

### numpy array の　condition

In [366]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.whwre

In [371]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [382]:
result, = np.where(array > 3)
result

array([4, 5, 6, 7, 8, 9])

In [380]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [381]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [384]:
ndarray = array.reshape(2, 5)
ndarray[ndarray > 3]

array([4, 5, 6, 7, 8, 9])

In [386]:
(ndarray > 3).all()

False

In [387]:
(ndarray > 3).any()

True

In [389]:
(ndarray > 3).all(axis=1)

array([False,  True])

### np.unique()

In [391]:
array = np.array([1, 1, 2 ,3 ,4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [392]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [394]:
np.unique(array, return_counts = True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

### np.bincount()

In [395]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

In [396]:
### np.concatenate()とnp.stack()

In [399]:
ndarray_even = np.arange(0, 18, 2).reshape(3,3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [400]:
ndarray_odd = np.arange(1, 19, 2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [405]:
np.concatenate([ndarray_even, ndarray_odd], axis=0)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [423]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [424]:
stacked_array = _

In [425]:
stacked_array.shape

(3, 3, 2)

### np.transpose  .T

In [426]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.84938931,  0.57124656, -0.19768097, -0.40169003],
       [-0.72858914,  1.13810473,  1.04804066,  0.81384787],
       [-1.28355871,  1.17259063, -1.46465421,  1.08542865]])

In [427]:
ndarray.shape

(3, 4)

In [428]:
ndarray.transpose()

array([[ 0.84938931, -0.72858914, -1.28355871],
       [ 0.57124656,  1.13810473,  1.17259063],
       [-0.19768097,  1.04804066, -1.46465421],
       [-0.40169003,  0.81384787,  1.08542865]])

In [429]:
ndarray.transpose().shape

(4, 3)

In [430]:
ndarray.T

array([[ 0.84938931, -0.72858914, -1.28355871],
       [ 0.57124656,  1.13810473,  1.17259063],
       [-0.19768097,  1.04804066, -1.46465421],
       [-0.40169003,  0.81384787,  1.08542865]])

In [431]:
np.transpose(ndarray)

array([[ 0.84938931, -0.72858914, -1.28355871],
       [ 0.57124656,  1.13810473,  1.17259063],
       [-0.19768097,  1.04804066, -1.46465421],
       [-0.40169003,  0.81384787,  1.08542865]])

## np.save('path', array)とnp.load('path')

In [433]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [439]:
np.save('sample_ndarray.npy', ndarray)

In [441]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [443]:
dictionary = {
    'id': 123456,
    'image': ndarray
}

In [447]:
np.save('sample_dict.npy', dictionary)

In [456]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)[()]

In [457]:
loaded_dict

{'id': 123456,
 'image': array([[[ 1.42986466, -0.08223231, -1.16918043, -0.06857261,
          -0.36524217],
         [ 0.61785261,  0.31450444,  1.27984041, -0.18703823,
           0.40112517],
         [ 0.10911095, -1.77082508, -0.12616947, -0.49411658,
          -2.60375062],
         [ 1.0343223 , -1.08649578, -1.7172237 , -0.69850758,
          -0.48012791]],
 
        [[ 0.0352849 ,  0.35182146, -0.46507689, -1.79626132,
           0.24220823],
         [-1.19068595,  1.24464973, -1.57506281,  0.71118001,
           0.60758872],
         [-1.06786257, -0.98561768, -0.44220674, -0.34908394,
           1.53261221],
         [-2.20494163,  0.99888944, -1.92135068,  0.34691628,
          -0.18570061]],
 
        [[ 0.11317526, -1.81483328,  0.25750822, -1.55534455,
          -1.1014135 ],
         [ 0.98450749, -1.17770038, -0.40969988, -0.4700702 ,
          -0.23491641],
         [-1.05847582, -0.57300912, -0.63657122, -0.65453184,
          -1.1032317 ],
         [ 0.89418868,  

In [452]:
a = np.array({'a': 1})

In [453]:
a

array({'a': 1}, dtype=object)

In [454]:
a[()]

{'a': 1}