## ニューラルネットワークの流れ

### PyTorch の準備

In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cpu'

### 全結合層の定義

In [3]:
import torch.nn as nn

In [19]:
# 乱数のシードを固定して再現性を確保
# CPU のシードを固定
torch.manual_seed(1)

In [7]:
# 全結合層の定義
fc = nn.Linear(3, 2)

In [9]:
# 重み　
fc.weight

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)

In [10]:
# バイアス
fc.bias

Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)

### 線形変換

In [11]:
# リストから PyTorch の Tensor に変換
x = torch.tensor([[1, 2, 3]])

In [12]:
type(x)

torch.Tensor

In [13]:
# 線形変換
u = fc(x)

RuntimeError: mat1 and mat2 must have the same dtype

In [14]:
# 詳細なデータ型の確認
x.dtype

torch.int64

In [15]:
# float32 に変換
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)

In [17]:
print(x, x.dtype)

tensor([[1., 2., 3.]]) torch.float32


In [18]:
# 線形変換
u = fc(x)
u

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward0>)

### 非線形変換

In [20]:
import torch.nn.functional as F

In [21]:
# ReLU 関数
z = F.relu(u)
z

tensor([[0.0000, 0.5164]], grad_fn=<ReluBackward0>)

### 目的関数

In [32]:
# 目標値
t = torch.tensor([[1]], dtype=torch.float)
t

tensor([[1.]])

In [34]:
# 平均二乗誤差
loss = F.mse_loss(t, y)
loss

tensor(0.7201, grad_fn=<MseLossBackward0>)

## ニューラルネットワークの実装（基礎）

In [36]:
# Step 1 : データセットを準備
# Step 2 : モデルを定義
# Step 3 : 目的関数を選択
# Step 4 : 最適化手法を選択
# Step 5 : モデルを学習

### データセットを準備

In [37]:
from sklearn.datasets import load_iris

# Iris データセットの読み込み
x, t = load_iris(return_X_y=True)

c:\Users\ytchi\anaconda3\envs\py37\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [38]:
# 形の確認
x.shape, t.shape

((150, 4), (150,))

In [39]:
# 型の確認
type(x), type(t)

(numpy.ndarray, numpy.ndarray)

In [42]:
import torch 
import torch.nn as nn
import torch.nn.functional as F