## Tensorの基礎

In [25]:
import torch
import numpy as np
# 乱数の種を固定
torch.manual_seed(42)

### Tensorの作成

In [8]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)

Tensor from list: tensor([1, 2, 3, 4])


In [9]:
type(tensor_from_list)

torch.Tensor

In [10]:
# intのリストで作成したTensorのデータ形はint64
tensor_from_list.dtype

torch.int64

In [11]:
# floatのlistで作ったtensorはfloat32
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)
tensor_from_list.dtype

Tensor from list: tensor([1., 2., 3., 4.])


torch.float32

In [16]:
# dtype引数でデータ型を指定
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

### Tensor作成

In [26]:
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
eye_tensor = torch.eye(3)
random_tensor = torch.rand((2, 3))

In [27]:
print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(random_tensor, random_tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) torch.float32


In [29]:
# NumPyとの対応
np_zeros = np.zeros((2, 3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
np_random = np.random.rand(2, 3)
# Numpy Arrayのデフォルトはfloat64であることに注意
print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.33363329 0.38410748 0.94200786]
 [0.50446434 0.43901587 0.35210996]] float64


In [31]:
# Tensorのshapeを表示
zeros_tensor.shape

torch.Size([2, 3])

### Tensorの操作