## Tensorの基礎

In [1]:
import torch
import numpy as np
# 乱数の種を固定
torch.manual_seed(42)

### Tensorの作成

In [8]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)

Tensor from list: tensor([1, 2, 3, 4])


In [9]:
type(tensor_from_list)

torch.Tensor

In [10]:
# intのリストで作成したTensorのデータ形はint64
tensor_from_list.dtype

torch.int64

In [11]:
# floatのlistで作ったtensorはfloat32
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)
tensor_from_list.dtype

Tensor from list: tensor([1., 2., 3., 4.])


torch.float32

In [16]:
# dtype引数でデータ型を指定
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

### Tensor作成

In [26]:
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
eye_tensor = torch.eye(3)
random_tensor = torch.rand((2, 3))

In [27]:
print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(random_tensor, random_tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) torch.float32


In [29]:
# NumPyとの対応
np_zeros = np.zeros((2, 3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
np_random = np.random.rand(2, 3)
# Numpy Arrayのデフォルトはfloat64であることに注意
print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.33363329 0.38410748 0.94200786]
 [0.50446434 0.43901587 0.35210996]] float64


In [31]:
# Tensorのshapeを表示
zeros_tensor.shape

torch.Size([2, 3])

### Tensorの操作

In [3]:
tensor_example = torch.rand((2, 3, 4))
np_example = np.random.rand(2, 3, 4)
print(tensor_example, np_example)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]]) [[[0.12888839 0.06892822 0.93796238 0.16430782]
  [0.27024205 0.01265678 0.68598949 0.00123841]
  [0.59747782 0.56905327 0.80361415 0.03402036]]

 [[0.28913533 0.61300381 0.75102186 0.50114811]
  [0.94052028 0.91244332 0.41554974 0.88407317]
  [0.10938161 0.1582489  0.23327945 0.3910318 ]]]


In [4]:
tensor_example.shape

torch.Size([2, 3, 4])

In [5]:
np_example.shape

(2, 3, 4)

In [16]:
# 転置
permuted_tensor = torch.permute(tensor_example, (1, 0, 2))
transposed_np = np.transpose(np_example, (1, 0, 2))
print("Original shape of tensor:", tensor_example.shape)
print("Permuted tensor:", permuted_tensor.shape)
print("Transposed numpy array:", transposed_np.shape)
print()

transposed_tensor = torch.transpose(tensor_example, 0, 1)
print("Original shape of tensor:", tensor_example.shape)
print("Transposed tensor:", transposed_tensor.shape)

# 二次元(rankが2つのtensor)の場合は .T / .t()

Original shape of tensor: torch.Size([2, 3, 4])
Permuted tensor: torch.Size([3, 2, 4])
Transposed numpy array: (3, 2, 4)

Original shape of tensor: torch.Size([2, 3, 4])
Transposed tensor: torch.Size([3, 2, 4])


In [14]:
# reshape
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_np = np.reshape(np_example, (6, 4))
# 結果を表示
print("Original shape of tensor:", tensor_example.shape)
print("Reshaped tensor:", reshaped_tensor.shape)
print("Reshaped numpy array:", reshaped_np.shape)

Original shape of tensor: torch.Size([2, 3, 4])
Reshaped tensor: torch.Size([6, 4])
Reshaped numpy array: (6, 4)


In [17]:
# 基本的には元のメモリをそのまま使っている
# reshape後のtensorを変更すると，元のtensorも変更されている
print(tensor_example[0])
reshaped_tensor[0] = 0
print(tensor_example[0])

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [33]:
# メモリが連続でなければreshape後のtensorはコピーを返す
# 連続的なメモリレイアウトを持つTensorを作成
x = torch.tensor([[1, 2], [3, 4], [5, 6]])

# 連続的なメモリレイアウトを持たない部分Tensorを取得 (transposed tensor)
y = x.T

# y は非連続的なメモリレイアウトを持つことを確認
print(y.is_contiguous())  # False が出力される

# reshape を使用して y の形状を変更
z = y.reshape(-1)
# 以下はエラーになる(viewはメモリが連続の場合のみ使える)
# viewを使って形状変更していれば、不意にコピーが作られメモリを浪費することがない
# z = y.view(-1)

# z が y とメモリを共有していないことを確認 (コピーが作成されたことを意味する)
print(z.data_ptr() == y.data_ptr())  # False が出力される

False
False


In [35]:
# flatten
flattened_tensor = torch.flatten(tensor_example)
flattened_np = np_example.flatten()
print("Flattened tensor:", flattened_tensor.shape)
print("Flattened numpy array:", flattened_np.shape)

Flattened tensor: torch.Size([24])
Flattened numpy array: (24,)


In [39]:
# squeeze（サイズが1の次元を削除）
tensor_example = torch.tensor([[[1], [2], [3]]])
np_example = np.array([[[1], [2], [3]]])
print(tensor_example.shape)
print(np_example.shape)

torch.Size([1, 3, 1])
(1, 3, 1)


In [40]:
squeezed_tensor = torch.squeeze(tensor_example) # 形状が(3,)になる
squeezed_np = np.squeeze(np_example) # 形状が(3,)になる
print("Squeezed tensor:", squeezed_tensor.shape)
print("Squeezed numpy array:", squeezed_np.shape)

Squeezed tensor: torch.Size([3])
Squeezed numpy array: (3,)


In [45]:
print(tensor_example)
print(squeezed_tensor)

tensor([[[1],
         [2],
         [3]]])
tensor([1, 2, 3])


In [50]:
# unsqueeze（指定した位置に新しい次元を追加）
unsqueeze_tensor = torch.unsqueeze(tensor_example, 0) # 0次元目に新しい次元を追加
expand_dims_np = np.expand_dims(np_example, 0) # 0次元目に新しい次元を追加
print("Unsqueezed tensor:", unsqueeze_tensor.shape)
print("Unsqueezed numpy array:", expand_dims_np.shape)

Unsqueezed tensor: torch.Size([1, 1, 3, 1])
Unsqueezed numpy array: (1, 1, 3, 1)


In [51]:
# unsqueezeと同様の操作
tensor_example[None, :, :, :].shape

torch.Size([1, 1, 3, 1])

## Tensorの便利関数

In [53]:
# サンプルのTensorとNumpy Array作成
tensor_example = torch.rand((2, 3))
np_example = np.random.rand(2, 3)
print(tensor_example)
print(np_example)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
[[0.68556402 0.38211277 0.71377786]
 [0.72841313 0.04084506 0.35560034]]


In [63]:
# 合計
sum_tensor = torch.sum(tensor_example)
sum_np = np.sum(np_example)

# # 平均
mean_tensor = torch.mean(tensor_example)
mean_np = np.mean(np_example)

# 標準偏差
std_tensor = torch.std(tensor_example)
std_np = np.std(np_example)

# 平方根
sqrt_tensor = torch.sqrt(tensor_example)
sqrt_np = np.sqrt(np_example)

# 結果を表示
print("Sum of tensor:", sum_tensor)
print("Sum of numpy array:", sum_np)
print("Mean of tensor:", mean_tensor)
print("Mean of numpy array:", mean_np)
print("Standard deviation of tensor:", std_tensor)
print("Standard deviation of numpy array:", std_np)
print("Square root of tensor:", sqrt_tensor)
print("Square root of numpy array:", sqrt_np)

Sum of tensor: tensor(1.4863)
Sum of numpy array: 2.9063131981624037
Mean of tensor: tensor(0.2477)
Mean of numpy array: 0.48438553302706727
Standard deviation of tensor: tensor(0.1916)
Standard deviation of numpy array: 0.25047175091564383
Square root of tensor: tensor([[0.3245, 0.5191, 0.5990],
        [0.4465, 0.7397, 0.0785]])
Square root of numpy array: [[0.82798794 0.61815271 0.84485375]
 [0.85347123 0.20210161 0.59632235]]


### 行列の演算

### 加減算+要素毎の乗除算

In [2]:
# 3x3のTensorを作成
a = torch.rand((3, 3))
b = torch.rand((3, 3))
print(a)
print(b)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [6]:
# 加減算および要素毎の剰余算
add = a + b
sub = a - b
mul = a * b
div = a / b

tensor([[6.6243, 0.9790, 0.6450],
        [1.1034, 0.6878, 0.8108],
        [0.5975, 0.8963, 1.6392]])


In [7]:
# 行列の積
mm = torch.mm(a, b)
matmul = torch.matmul(a, b)
at_op = a @ b
print(mm)
print(matmul)
print(at_op)

tensor([[1.0774, 1.6830, 1.4215],
        [0.7253, 1.6503, 1.2036],
        [1.1281, 1.5234, 1.2804]])
tensor([[1.0774, 1.6830, 1.4215],
        [0.7253, 1.6503, 1.2036],
        [1.1281, 1.5234, 1.2804]])
tensor([[1.0774, 1.6830, 1.4215],
        [0.7253, 1.6503, 1.2036],
        [1.1281, 1.5234, 1.2804]])


### ブロードキャスティング

In [8]:
# 3x3のTensorを作成
a = torch.rand((3, 3))
scalar = 5
result1 = a + scalar
print(a)
print(result1)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
tensor([[5.2666, 5.6274, 5.2696],
        [5.4414, 5.2969, 5.8317],
        [5.1053, 5.2695, 5.3588]])


In [10]:
# (3, 3)と(1, 3)の演算
b = torch.rand(1, 3)
result2 = a + b
print(a)
print(b)
print(result2)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
tensor([[0.9516, 0.0753, 0.8860]])
tensor([[1.2181, 0.7027, 1.1556],
        [1.3929, 0.3722, 1.7177],
        [1.0569, 0.3448, 1.2448]])


In [11]:
# (32, 128, 128, 3)と(128, 128, 3)の演算
c = torch.rand((32, 128, 128, 3))
d = torch.rand((128, 128, 3))
result3 = c + d
print(result3.shape)

torch.Size([32, 128, 128, 3])


In [13]:
# (32, 128, 128, 3)と(128, 128, 6)の演算は形状が不一致なためエラー
c = torch.rand((32, 128, 128, 3))
d = torch.rand((128, 128, 6))
# 以下はエラー
# result3 = c + d
# print(result3.shape)

In [14]:
# (1, 128, 128, 3)と(8, 128, 128, 1)の演算
e = torch.rand((1, 128, 128, 3))
f = torch.rand((8, 128, 128, 1))
result4 = e + f
print(result4.shape)

torch.Size([8, 128, 128, 3])
